### ISSUE TITLE
[mood] ability to strip moods from the binary at build time

### ISSUE THREAD

**Issue by Gankra** [Gankra/cargo-mommy#30]
I'm not 100% sure how i'd want it to be impl the interface for it, but some people are concerned about the more spicy mood strings being in the binary, so it would be nice to have a way to maybe do like --no-default-features and have only chill mode.

The only place that really needs to change is here:

https://github.com/Gankra/cargo-mommy/blob/aa7801b3a69d789d52a72436c94cfdd8c6fe6e12/build.rs#L40C15-L56

break up the string formatting into several iterative steps, then disable the ones you don't want in the binary (forget if build.rs makes reading features messy).

**Comment by 5225225** [comment]
I'll look into this, from what I can tell you can just use `cfg!` inside a build.rs (https://stackoverflow.com/a/66843072), so I'm thinking having

```toml
[features]
# This affects if a given response is *supported* in the built binary,
# not if it's enabled by default
default = ["chill", "thirsty", "yikes"]

chill = []
thirsty = []
yikes = []
```

Haven't *tested* if cfg! works to read features, but they're definitely at least exposed as envars, which wouldn't be *too* bad to read, and the installation method would be like `cargo install cargo-mommy --no-default-features -F chill`. (nixpkgs could probably just expose it as overridable options? not entirely sure how package config works there).
